<?php

// Include DatabaseHelper.php file
require_once('DatabaseHelpKunde.php');

// Instantiate DatabaseHelper class
$database = new DatabaseHelper();

// Get parameter 'email', 'username' and 'passwort' from GET Request
// Btw. you can see the parameters in the URL if they are set
$email = '';
if (isset($_GET['email'])) {
    $email = $_GET['email'];
}

$username = '';
if (isset($_GET['username'])) {
    $username = $_GET['username'];
}

$passwort = '';
if (isset($_GET['passwort'])) {
    $passwort = $_GET['passwort'];
}

//Fetch data from database
$kunde_array = $database->selectAllKunden($email, $username, $passwort);
?>


<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body{
            font-family: 'Futura', sans-serif;
        }
        </style>
</head>
<body>
<br>
<h1>
<a href="index.php">ZOLA</a>
    </h1>
<h1>Data from 'Kunde'</h1>

<h2>
    <a href="alleKunden.php">Alle Kunde</a>
</h2>


<!-- Add Kunde -->
<h2>Add Kunde: </h2>
<form method="post" action="addKunde.php">
    <!-- ID is not needed, because its autogenerated by the database -->

    <!-- Email textbox -->
    <div>
        <label for="new_email">Email:</label>
        <input id="new_email" name="email" type="text" maxlength="20">
    </div>
    <br>

    <!-- Username textbox -->
    <div>
        <label for="new_username">Username:</label>
        <input id="new_username" name="username" type="text" maxlength="20">
    </div>
    <br>

     <!-- Passwort textbox -->
     <div>
        <label for="new_passwort">Passwort:</label>
        <input id="new_passwort" name="passwort" type="text" maxlength="20">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button type="submit">
            Add Kunde
        </button>
    </div>
</form>
<br>
<hr>

<!-- Delete Person -->
<h2>Delete Kunde: </h2>
<form method="post" action="delKunde.php">
    <!-- ID textbox -->
    <div>
        <label for="del_email">Email:</label>
        <input id="del_email" name="email" type="text" min="1">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button type="submit">
            Delete Kunde
        </button>
    </div>
</form>
<br>
<hr>

<!-- Search form -->
<h2>Kunde Search:</h2>
<form method="get">
    <!-- ID textbox:-->
    <div>
        <label for="username">Username:</label>
        <input id="username" name="username" type="text" value='<?php echo $username; ?>' min="1">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button id='submit' type='submit'>
            Search
        </button>
    </div>
</form>
<br>
<hr>

<!-- Search result -->
<h2>Kunde Search Result:</h2>
<table>
    <tr>
        <th>Username</th>
    </tr>
    <?php foreach ($kunde_array as $kundex) : ?>
        <tr>
            <td><?php echo $kundex['EMAIL']; ?>  </td>
            <td><?php echo $kundex['USERNAME']; ?>  </td>
            <td><?php echo $kundex['PASSWORT']; ?>  </td>
        </tr>
    <?php endforeach; ?>
</table>
    
</body>
</html>